language: python
python:
  - 3.3
  - 3.4
  - 3.5
install:
  - python setup.py install
  - pip install coverage
script:
  - python setup.py nosetests --with-coverage --cover-erase --cover-package defopt
  - coverage report --fail-under 100
